# .github/workflows/deploy.yml

name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      # 2. Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Specify Ruby version
          bundler-cache: true # Caches installed gems

      # 3. Install dependencies
      - name: Install Dependencies
        run: bundle install

      # 4. Build the Jekyll site
      - name: Build Jekyll Site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      # 5. Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: false
          keep_files: true
