name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # 3) Install any dependencies from your Gemfile
      - name: Install dependencies
        run: bundle install

      # 4) Optionally configure Pages (adds some ENV vars) 
      - name: Configure Pages
        uses: actions/configure-pages@v3

      # 5) Build with Jekyll
      - name: Build Jekyll
        run: |
          bundle exec jekyll build --trace
          ls -la _site/
        env:
          JEKYLL_ENV: production

      # 6) Upload the built site as an artifact (name = "github-pages")
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: _site/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      # optionally capture the URL of the deployment
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      # 7) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: your-custom-name   # Must match the name above
